# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WoTDJTLipJlYgdcQrC9551ta7-JZfGro

Задача 42: Узнать какая максимальная households в зоне минимального значения population
"""

import pandas as pd
df = pd.read_csv("sample_data/california_housing_train.csv")

df[df['population'] == df['population'].min()]['households'].max()